<?php

namespace Weble\JoomlaCommands\Application;

use Joomla\CMS\Application\CliApplication;
use Joomla\CMS\Application\CMSApplication;
use Joomla\CMS\Factory;
use Joomla\CMS\Plugin\PluginHelper;
use Joomla\Registry\Registry;
use Joomla\Uri\Uri;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class Application extends \Symfony\Component\Console\Application
{
    /**
     * @var InputInterface
     */
    protected $input;
    /**
     * @var OutputInterface
     */
    protected $output;
    /**
     * @var CliApplication
     */
    protected $joomlaCliApplication;

    public function doRun(InputInterface $input, OutputInterface $output)
    {
        $this->input = $input;
        $this->output = $output;

        $this->configureJoomlaApplication();
        $this->fixUriIssues();
        $this->loadCommandsFromPlugins();


        return parent::doRun($input, $output); // TODO: Change the autogenerated stub
    }

    public function setJoomlaCliApplication(CliApplication $app): self
    {
        $this->joomlaCliApplication = $app;
        return $this;
    }

    protected function configureJoomlaApplication()
    {
        $clientId = $this->input->hasParameterOption(['--site'], true) ?: 'site';
        $application = CMSApplication::getInstance($clientId);

        Factory::$application = $application;
    }

    protected function loadCommandsFromPlugins()
    {
        PluginHelper::importPlugin('system', null, true);
        PluginHelper::importPlugin('console', null, true);
        $this->joomlaCliApplication->triggerEvent('onGetConsoleCommands', [$this]);
    }

    /**
     * Here we try to fix any action (like using JRoute::_) inside a queued message
     * Since we run in cli, we don't have access to the request, and jroute can't guess things
     * like current uri, host, etc.
     * So we take the configured domain in your SEF plugin (which you should have populate to fix possible
     * SEO issues anyway) and use that as a HOST.
     */
    protected function fixUriIssues(): void
    {
        $domain = 'https://localhost/';

        $params = new Registry(PluginHelper::getPlugin('system', 'sef')->params);
        $domain = $params->get('domain') ?: $domain;
        $uri = new Uri($domain);

        $_SERVER['REQUEST_URI'] = '/';
        $_SERVER['HTTP_HOST'] = $uri->getHost();
        $_SERVER['HTTPS'] = stripos($domain, 'https') === 0;
    }
}
